<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;

class CreateItems extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::unprepared("
			CREATE TABLE itemcategories(
				id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
				name VARCHAR(50) NOT NULL,
				iconstring VARCHAR(32) NOT NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
				updated_at TIMESTAMP NULL
			);

			CREATE TABLE items(
				id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
				itemcategory_id INT UNSIGNED NOT NULL,
				name VARCHAR(50) NOT NULL,
				description TEXT NULL,
				imageurl VARCHAR(200) NULL,
				startbidamount INT UNSIGNED NOT NULL COMMENT 'no decimal needed',
				endbidamount INT UNSIGNED NULL COMMENT 'no decimal needed',
				endbid_by INT UNSIGNED NULL,
				status ENUM('Draft', 'Draft', 'Sold') NOT NULL DEFAULT 'Draft',
				created_by INT UNSIGNED NOT NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
				updated_at TIMESTAMP NULL
			);

			CREATE TABLE itemusers(
				id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
				item_id INT UNSIGNED NOT NULL,
				user_id INT UNSIGNED NOT NULL,
				bidamount INT UNSIGNED NOT NULL COMMENT 'no decimal needed',
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
				updated_at TIMESTAMP NULL
			);

			CREATE TABLE users(
				id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
				userkey VARCHAR(10) NOT NULL UNIQUE,
				name VARCHAR(50) NOT NULL,
				password CHAR(60) NOT NULL,
				maxbidamount INT UNSIGNED NOT NULL COMMENT 'for automated bid amount',
				gender ENUM('Male', 'Female') NOT NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
				updated_at TIMESTAMP NULL
			);

			CREATE INDEX itemusers_fkindex
			ON itemusers (item_id, user_id);
			CREATE INDEX item_fkindex
			ON items (itemcategory_id, name);
			CREATE INDEX user_fkindex
			ON users (userkey);

			ALTER TABLE itemusers
			ADD CONSTRAINT reject_double UNIQUE(item_id, bidamount);

			INSERT INTO users 
			VALUES
				(NULL, 'user1', 'Indra Saswita', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 100, 'Male', NOW(), NOW()),
				(NULL, 'user2', 'Septiana Rahayu Dewi', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 50, 'Female', NOW(), NOW()),
				(NULL, 'user3', 'Peter James', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 70, 'Male', NOW(), NOW()),
				(NULL, 'user4', 'Kezia Gracel Gold', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 80, 'Female', NOW(), NOW()),
				(NULL, 'user5', 'Calvina Izumi Khumarga', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 70, 'Male', NOW(), NOW()),
				(NULL, 'user6', 'Oldyson Anggoro', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 0, 'Female', NOW(), NOW()),
				(NULL, 'user7', 'Remi Rafael', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 170, 'Male', NOW(), NOW()),
				(NULL, 'user8', 'Catherine Natalia', '$2y$10\$BnrCjG8mC6BnsTxC4D83N.MzRY7CSZQ5VYDOfhIAs/ajhkqJ0T8Ym', 0, 'Female', NOW(), NOW());

			INSERT INTO items
			VALUES 
				(NULL, 6, 'book', 'This is the description of Book. And <i>Book</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #1. 4562', 'https://poke.indrasaswita.com/sprites/animated/1.gif', 40, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 9, 'boom box', 'This is the description of Boom Box. And <i>Boom Box</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #2. 2216', 'https://poke.indrasaswita.com/sprites/animated/2.gif', 90, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 4, 'bottle of water', 'This is the description of Bottle Of Water. And <i>Bottle Of Water</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #3. 8387', 'https://poke.indrasaswita.com/sprites/animated/3.gif', 10, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 2, 'wedding ring', 'This is the description of Wedding Ring. And <i>Wedding Ring</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #4. 8409', 'https://poke.indrasaswita.com/sprites/animated/4.gif', 30, 146, 2, 'Sold', 7, NOW(), NOW()),
				(NULL, 10, 'flyswatter', 'This is the description of Flyswatter. And <i>Flyswatter</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #5. 1897', 'https://poke.indrasaswita.com/sprites/animated/5.gif', 100, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 1, 'sand paper', 'This is the description of Sand Paper. And <i>Sand Paper</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #6. 6034', 'https://poke.indrasaswita.com/sprites/animated/6.gif', 90, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 7, 'tube of lip balm', 'This is the description of Tube Of Lip Balm. And <i>Tube Of Lip Balm</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #7. 4696', 'https://poke.indrasaswita.com/sprites/animated/7.gif', 20, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 5, 'remote', 'This is the description of Remote. And <i>Remote</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #8. 4329', 'https://poke.indrasaswita.com/sprites/animated/8.gif', 90, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 3, 'novel', 'This is the description of Novel. And <i>Novel</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #9. 5173', 'https://poke.indrasaswita.com/sprites/animated/9.gif', 30, 127, 2, 'Sold', 5, NOW(), NOW()),
				(NULL, 6, 'bangle bracelet', 'This is the description of Bangle Bracelet. And <i>Bangle Bracelet</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #10. 9923', 'https://poke.indrasaswita.com/sprites/animated/10.gif', 90, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 9, 'stop sign', 'This is the description of Stop Sign. And <i>Stop Sign</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #11. 3158', 'https://poke.indrasaswita.com/sprites/animated/11.gif', 90, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 5, 'can of chili', 'This is the description of Can Of Chili. And <i>Can Of Chili</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #12. 9293', 'https://poke.indrasaswita.com/sprites/animated/12.gif', 40, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 6, 'lighter', 'This is the description of Lighter. And <i>Lighter</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #13. 3419', 'https://poke.indrasaswita.com/sprites/animated/13.gif', 70, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 4, 'dolphin', 'This is the description of Dolphin. And <i>Dolphin</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #14. 6199', 'https://poke.indrasaswita.com/sprites/animated/14.gif', 40, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 7, 'tennis ball', 'This is the description of Tennis Ball. And <i>Tennis Ball</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #15. 7650', 'https://poke.indrasaswita.com/sprites/animated/15.gif', 10, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 6, 'camera', 'This is the description of Camera. And <i>Camera</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #16. 6017', 'https://poke.indrasaswita.com/sprites/animated/16.gif', 50, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 9, 'mp3 player', 'This is the description of Mp3 Player. And <i>Mp3 Player</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #17. 8391', 'https://poke.indrasaswita.com/sprites/animated/17.gif', 80, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 10, 'squirrel', 'This is the description of Squirrel. And <i>Squirrel</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #18. 3524', 'https://poke.indrasaswita.com/sprites/animated/18.gif', 60, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 1, 'bar of soap', 'This is the description of Bar Of Soap. And <i>Bar Of Soap</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #19. 6737', 'https://poke.indrasaswita.com/sprites/animated/19.gif', 60, 112, 7, 'Sold', 1, NOW(), NOW()),
				(NULL, 3, 'ice cube', 'This is the description of Ice Cube. And <i>Ice Cube</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #20. 1915', 'https://poke.indrasaswita.com/sprites/animated/20.gif', 70, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 7, 'pair of binoculars', 'This is the description of Pair Of Binoculars. And <i>Pair Of Binoculars</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #21. 9456', 'https://poke.indrasaswita.com/sprites/animated/21.gif', 70, 185, 5, 'Sold', 5, NOW(), NOW()),
				(NULL, 8, 'class ring', 'This is the description of Class Ring. And <i>Class Ring</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #22. 2165', 'https://poke.indrasaswita.com/sprites/animated/22.gif', 40, 182, 4, 'Sold', 6, NOW(), NOW()),
				(NULL, 7, 'garden spade', 'This is the description of Garden Spade. And <i>Garden Spade</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #23. 5742', 'https://poke.indrasaswita.com/sprites/animated/23.gif', 80, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 3, 'map', 'This is the description of Map. And <i>Map</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #24. 6940', 'https://poke.indrasaswita.com/sprites/animated/24.gif', 40, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 2, 'plush frog', 'This is the description of Plush Frog. And <i>Plush Frog</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #25. 6854', 'https://poke.indrasaswita.com/sprites/animated/25.gif', 70, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 2, 'toy plane', 'This is the description of Toy Plane. And <i>Toy Plane</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #26. 6754', 'https://poke.indrasaswita.com/sprites/animated/26.gif', 30, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 10, 'tomato', 'This is the description of Tomato. And <i>Tomato</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #27. 4445', 'https://poke.indrasaswita.com/sprites/animated/27.gif', 50, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 5, 'shirt', 'This is the description of Shirt. And <i>Shirt</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #28. 2728', 'https://poke.indrasaswita.com/sprites/animated/28.gif', 80, 106, 5, 'Sold', 8, NOW(), NOW()),
				(NULL, 7, 'lime', 'This is the description of Lime. And <i>Lime</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #29. 8375', 'https://poke.indrasaswita.com/sprites/animated/29.gif', 50, 144, 2, 'Sold', 6, NOW(), NOW()),
				(NULL, 3, 'plate', 'This is the description of Plate. And <i>Plate</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #30. 6356', 'https://poke.indrasaswita.com/sprites/animated/30.gif', 60, 125, 6, 'Sold', 1, NOW(), NOW()),
				(NULL, 6, 'sticky note', 'This is the description of Sticky Note. And <i>Sticky Note</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #31. 7631', 'https://poke.indrasaswita.com/sprites/animated/31.gif', 30, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 4, 'car', 'This is the description of Car. And <i>Car</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #32. 3289', 'https://poke.indrasaswita.com/sprites/animated/32.gif', 80, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 7, 'stick of incense', 'This is the description of Stick Of Incense. And <i>Stick Of Incense</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #33. 1525', 'https://poke.indrasaswita.com/sprites/animated/33.gif', 80, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 7, 'sandal', 'This is the description of Sandal. And <i>Sandal</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #34. 4057', 'https://poke.indrasaswita.com/sprites/animated/34.gif', 20, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 5, 'chain', 'This is the description of Chain. And <i>Chain</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #35. 8686', 'https://poke.indrasaswita.com/sprites/animated/35.gif', 50, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 6, 'hair tie', 'This is the description of Hair Tie. And <i>Hair Tie</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #36. 2898', 'https://poke.indrasaswita.com/sprites/animated/36.gif', 70, 137, 8, 'Sold', 7, NOW(), NOW()),
				(NULL, 5, 'light bulb', 'This is the description of Light Bulb. And <i>Light Bulb</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #37. 6806', 'https://poke.indrasaswita.com/sprites/animated/37.gif', 30, 177, 3, 'Sold', 4, NOW(), NOW()),
				(NULL, 3, 'roll of duct tape', 'This is the description of Roll Of Duct Tape. And <i>Roll Of Duct Tape</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #38. 5895', 'https://poke.indrasaswita.com/sprites/animated/38.gif', 40, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 8, 'laser pointer', 'This is the description of Laser Pointer. And <i>Laser Pointer</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #39. 6405', 'https://poke.indrasaswita.com/sprites/animated/39.gif', 100, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 3, 'pair of scissors', 'This is the description of Pair Of Scissors. And <i>Pair Of Scissors</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #40. 5230', 'https://poke.indrasaswita.com/sprites/animated/40.gif', 90, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 1, 'banana', 'This is the description of Banana. And <i>Banana</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #41. 3780', 'https://poke.indrasaswita.com/sprites/animated/41.gif', 70, 148, 1, 'Sold', 5, NOW(), NOW()),
				(NULL, 10, 'trucks', 'This is the description of Trucks. And <i>Trucks</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #42. 8026', 'https://poke.indrasaswita.com/sprites/animated/42.gif', 70, 177, 8, 'Sold', 6, NOW(), NOW()),
				(NULL, 5, 'bottle of pills', 'This is the description of Bottle Of Pills. And <i>Bottle Of Pills</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #43. 3474', 'https://poke.indrasaswita.com/sprites/animated/43.gif', 10, 179, 6, 'Sold', 8, NOW(), NOW()),
				(NULL, 9, 'milk', 'This is the description of Milk. And <i>Milk</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #44. 6028', 'https://poke.indrasaswita.com/sprites/animated/44.gif', 40, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 6, 'grocery list', 'This is the description of Grocery List. And <i>Grocery List</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #45. 6836', 'https://poke.indrasaswita.com/sprites/animated/45.gif', 50, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 2, 'bow tie', 'This is the description of Bow Tie. And <i>Bow Tie</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #46. 9692', 'https://poke.indrasaswita.com/sprites/animated/46.gif', 10, 123, 8, 'Sold', 4, NOW(), NOW()),
				(NULL, 7, 'can of whipped cream', 'This is the description of Can Of Whipped Cream. And <i>Can Of Whipped Cream</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #47. 4588', 'https://poke.indrasaswita.com/sprites/animated/47.gif', 60, 117, 1, 'Sold', 4, NOW(), NOW()),
				(NULL, 3, 'plush unicorn', 'This is the description of Plush Unicorn. And <i>Plush Unicorn</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #48. 2873', 'https://poke.indrasaswita.com/sprites/animated/48.gif', 70, 116, 4, 'Sold', 8, NOW(), NOW()),
				(NULL, 4, 'hair brush', 'This is the description of Hair Brush. And <i>Hair Brush</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #49. 8297', 'https://poke.indrasaswita.com/sprites/animated/49.gif', 30, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 5, 'glasses', 'This is the description of Glasses. And <i>Glasses</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #50. 3432', 'https://poke.indrasaswita.com/sprites/animated/50.gif', 70, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 1, 'bottle cap', 'This is the description of Bottle Cap. And <i>Bottle Cap</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #51. 5757', 'https://poke.indrasaswita.com/sprites/animated/51.gif', 80, 184, 6, 'Sold', 6, NOW(), NOW()),
				(NULL, 3, 'locket', 'This is the description of Locket. And <i>Locket</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #52. 9411', 'https://poke.indrasaswita.com/sprites/animated/52.gif', 40, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 3, 'kitchen knife', 'This is the description of Kitchen Knife. And <i>Kitchen Knife</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #53. 9861', 'https://poke.indrasaswita.com/sprites/animated/53.gif', 50, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 1, 'drill press', 'This is the description of Drill Press. And <i>Drill Press</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #54. 3306', 'https://poke.indrasaswita.com/sprites/animated/54.gif', 100, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 9, 'keyboard', 'This is the description of Keyboard. And <i>Keyboard</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #55. 8819', 'https://poke.indrasaswita.com/sprites/animated/55.gif', 60, 181, 2, 'Sold', 6, NOW(), NOW()),
				(NULL, 10, 'quilt', 'This is the description of Quilt. And <i>Quilt</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #56. 7671', 'https://poke.indrasaswita.com/sprites/animated/56.gif', 50, 131, 8, 'Sold', 5, NOW(), NOW()),
				(NULL, 10, 'tissue box', 'This is the description of Tissue Box. And <i>Tissue Box</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #57. 1673', 'https://poke.indrasaswita.com/sprites/animated/57.gif', 60, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 3, 'clay pot', 'This is the description of Clay Pot. And <i>Clay Pot</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #58. 5763', 'https://poke.indrasaswita.com/sprites/animated/58.gif', 10, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 5, 'clothes pin', 'This is the description of Clothes Pin. And <i>Clothes Pin</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #59. 7457', 'https://poke.indrasaswita.com/sprites/animated/59.gif', 30, 192, 8, 'Sold', 8, NOW(), NOW()),
				(NULL, 4, 'wallet', 'This is the description of Wallet. And <i>Wallet</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #60. 9912', 'https://poke.indrasaswita.com/sprites/animated/60.gif', 10, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 9, 'lion', 'This is the description of Lion. And <i>Lion</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #61. 9234', 'https://poke.indrasaswita.com/sprites/animated/61.gif', 40, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 2, 'glow stick', 'This is the description of Glow Stick. And <i>Glow Stick</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #62. 2345', 'https://poke.indrasaswita.com/sprites/animated/62.gif', 80, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 4, 'trash bag', 'This is the description of Trash Bag. And <i>Trash Bag</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #63. 5528', 'https://poke.indrasaswita.com/sprites/animated/63.gif', 80, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 1, 'pair of tongs', 'This is the description of Pair Of Tongs. And <i>Pair Of Tongs</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #64. 7147', 'https://poke.indrasaswita.com/sprites/animated/64.gif', 60, 188, 8, 'Sold', 2, NOW(), NOW()),
				(NULL, 1, 'tea pot', 'This is the description of Tea Pot. And <i>Tea Pot</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #65. 3838', 'https://poke.indrasaswita.com/sprites/animated/65.gif', 10, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 10, 'toothpick', 'This is the description of Toothpick. And <i>Toothpick</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #66. 5305', 'https://poke.indrasaswita.com/sprites/animated/66.gif', 20, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 2, 'blouse', 'This is the description of Blouse. And <i>Blouse</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #67. 9858', 'https://poke.indrasaswita.com/sprites/animated/67.gif', 30, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 2, 'pinecone', 'This is the description of Pinecone. And <i>Pinecone</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #68. 6885', 'https://poke.indrasaswita.com/sprites/animated/68.gif', 50, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 8, 'package of glitter', 'This is the description of Package Of Glitter. And <i>Package Of Glitter</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #69. 9045', 'https://poke.indrasaswita.com/sprites/animated/69.gif', 50, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 7, 'blowdryer', 'This is the description of Blowdryer. And <i>Blowdryer</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #70. 2914', 'https://poke.indrasaswita.com/sprites/animated/70.gif', 90, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 8, 'cars', 'This is the description of Cars. And <i>Cars</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #71. 3997', 'https://poke.indrasaswita.com/sprites/animated/71.gif', 80, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 5, 'panda', 'This is the description of Panda. And <i>Panda</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #72. 2163', 'https://poke.indrasaswita.com/sprites/animated/72.gif', 50, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 10, 'cookie jar', 'This is the description of Cookie Jar. And <i>Cookie Jar</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #73. 3698', 'https://poke.indrasaswita.com/sprites/animated/73.gif', 90, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 9, 'cellphone', 'This is the description of Cellphone. And <i>Cellphone</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #74. 4726', 'https://poke.indrasaswita.com/sprites/animated/74.gif', 30, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 6, 'plastic fork', 'This is the description of Plastic Fork. And <i>Plastic Fork</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #75. 1305', 'https://poke.indrasaswita.com/sprites/animated/75.gif', 10, 104, 5, 'Sold', 8, NOW(), NOW()),
				(NULL, 6, 'mirror', 'This is the description of Mirror. And <i>Mirror</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #76. 1320', 'https://poke.indrasaswita.com/sprites/animated/76.gif', 60, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 6, 'sidewalk', 'This is the description of Sidewalk. And <i>Sidewalk</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #77. 6257', 'https://poke.indrasaswita.com/sprites/animated/77.gif', 10, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 4, 'house', 'This is the description of House. And <i>House</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #78. 3725', 'https://poke.indrasaswita.com/sprites/animated/78.gif', 20, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 1, 'matchbook', 'This is the description of Matchbook. And <i>Matchbook</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #79. 2319', 'https://poke.indrasaswita.com/sprites/animated/79.gif', 20, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 8, 'needle', 'This is the description of Needle. And <i>Needle</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #80. 1281', 'https://poke.indrasaswita.com/sprites/animated/80.gif', 90, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 1, 'video games', 'This is the description of Video Games. And <i>Video Games</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #81. 5927', 'https://poke.indrasaswita.com/sprites/animated/81.gif', 50, 112, 8, 'Sold', 1, NOW(), NOW()),
				(NULL, 8, 'beef', 'This is the description of Beef. And <i>Beef</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #82. 9963', 'https://poke.indrasaswita.com/sprites/animated/82.gif', 40, 164, 1, 'Sold', 3, NOW(), NOW()),
				(NULL, 7, 'bottle of lotion', 'This is the description of Bottle Of Lotion. And <i>Bottle Of Lotion</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #83. 5340', 'https://poke.indrasaswita.com/sprites/animated/83.gif', 100, 124, 2, 'Sold', 3, NOW(), NOW()),
				(NULL, 8, 'fake flowers', 'This is the description of Fake Flowers. And <i>Fake Flowers</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #84. 4481', 'https://poke.indrasaswita.com/sprites/animated/84.gif', 60, 189, 6, 'Sold', 3, NOW(), NOW()),
				(NULL, 1, 'hair ribbon', 'This is the description of Hair Ribbon. And <i>Hair Ribbon</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #85. 6732', 'https://poke.indrasaswita.com/sprites/animated/85.gif', 80, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 9, 'bottle of soda', 'This is the description of Bottle Of Soda. And <i>Bottle Of Soda</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #86. 8151', 'https://poke.indrasaswita.com/sprites/animated/86.gif', 90, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 6, 'tire swing', 'This is the description of Tire Swing. And <i>Tire Swing</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #87. 2324', 'https://poke.indrasaswita.com/sprites/animated/87.gif', 30, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 5, 'rat', 'This is the description of Rat. And <i>Rat</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #88. 1914', 'https://poke.indrasaswita.com/sprites/animated/88.gif', 90, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 5, 'butter knife', 'This is the description of Butter Knife. And <i>Butter Knife</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #89. 5690', 'https://poke.indrasaswita.com/sprites/animated/89.gif', 100, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 7, 'dictionary', 'This is the description of Dictionary. And <i>Dictionary</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #90. 4040', 'https://poke.indrasaswita.com/sprites/animated/90.gif', 30, 200, 6, 'Sold', 5, NOW(), NOW()),
				(NULL, 6, 'pair of knitting needles', 'This is the description of Pair Of Knitting Needles. And <i>Pair Of Knitting Needles</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #91. 6834', 'https://poke.indrasaswita.com/sprites/animated/91.gif', 100, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 4, 'bowl', 'This is the description of Bowl. And <i>Bowl</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #92. 8313', 'https://poke.indrasaswita.com/sprites/animated/92.gif', 60, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 8, 'handheld game system', 'This is the description of Handheld Game System. And <i>Handheld Game System</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #93. 7517', 'https://poke.indrasaswita.com/sprites/animated/93.gif', 90, 148, 7, 'Sold', 5, NOW(), NOW()),
				(NULL, 7, 'computer', 'This is the description of Computer. And <i>Computer</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #94. 3175', 'https://poke.indrasaswita.com/sprites/animated/94.gif', 60, 141, 8, 'Sold', 2, NOW(), NOW()),
				(NULL, 2, 'bottle of paint', 'This is the description of Bottle Of Paint. And <i>Bottle Of Paint</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #95. 1208', 'https://poke.indrasaswita.com/sprites/animated/95.gif', 10, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 9, 'roll of toilet paper', 'This is the description of Roll Of Toilet Paper. And <i>Roll Of Toilet Paper</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #96. 5716', 'https://poke.indrasaswita.com/sprites/animated/96.gif', 60, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 5, 'toothpaste', 'This is the description of Toothpaste. And <i>Toothpaste</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #97. 4639', 'https://poke.indrasaswita.com/sprites/animated/97.gif', 100, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 4, 'ice cream stick', 'This is the description of Ice Cream Stick. And <i>Ice Cream Stick</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #98. 4257', 'https://poke.indrasaswita.com/sprites/animated/98.gif', 90, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 7, 'steak knife', 'This is the description of Steak Knife. And <i>Steak Knife</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #99. 3645', 'https://poke.indrasaswita.com/sprites/animated/99.gif', 100, 141, 1, 'Sold', 7, NOW(), NOW()),
				(NULL, 8, 'egg', 'This is the description of Egg. And <i>Egg</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #100. 1329', 'https://poke.indrasaswita.com/sprites/animated/100.gif', 40, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 5, 'comb', 'This is the description of Comb. And <i>Comb</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #101. 7179', 'https://poke.indrasaswita.com/sprites/animated/101.gif', 50, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 4, 'rubber stamp', 'This is the description of Rubber Stamp. And <i>Rubber Stamp</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #102. 3818', 'https://poke.indrasaswita.com/sprites/animated/102.gif', 50, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 10, 'teddies', 'This is the description of Teddies. And <i>Teddies</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #103. 2963', 'https://poke.indrasaswita.com/sprites/animated/103.gif', 30, 170, 8, 'Sold', 5, NOW(), NOW()),
				(NULL, 4, 'purse/bag', 'This is the description of Purse/Bag. And <i>Purse/Bag</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #104. 3118', 'https://poke.indrasaswita.com/sprites/animated/104.gif', 90, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 7, 'cat', 'This is the description of Cat. And <i>Cat</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #105. 5740', 'https://poke.indrasaswita.com/sprites/animated/105.gif', 10, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 2, 'bottle of perfume', 'This is the description of Bottle Of Perfume. And <i>Bottle Of Perfume</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #106. 7297', 'https://poke.indrasaswita.com/sprites/animated/106.gif', 50, 147, 1, 'Sold', 1, NOW(), NOW()),
				(NULL, 10, 'box of chocolates', 'This is the description of Box Of Chocolates. And <i>Box Of Chocolates</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #107. 5301', 'https://poke.indrasaswita.com/sprites/animated/107.gif', 50, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 2, 'football', 'This is the description of Football. And <i>Football</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #108. 8256', 'https://poke.indrasaswita.com/sprites/animated/108.gif', 90, 107, 1, 'Sold', 4, NOW(), NOW()),
				(NULL, 7, 'snail shell', 'This is the description of Snail Shell. And <i>Snail Shell</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #109. 9372', 'https://poke.indrasaswita.com/sprites/animated/109.gif', 50, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 9, 'spring', 'This is the description of Spring. And <i>Spring</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #110. 4845', 'https://poke.indrasaswita.com/sprites/animated/110.gif', 80, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 7, 'tree', 'This is the description of Tree. And <i>Tree</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #111. 2245', 'https://poke.indrasaswita.com/sprites/animated/111.gif', 70, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 7, 'thread', 'This is the description of Thread. And <i>Thread</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #112. 4052', 'https://poke.indrasaswita.com/sprites/animated/112.gif', 20, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 5, 'pair of safety goggles', 'This is the description of Pair Of Safety Goggles. And <i>Pair Of Safety Goggles</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #113. 2631', 'https://poke.indrasaswita.com/sprites/animated/113.gif', 100, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 10, 'mouse pad', 'This is the description of Mouse Pad. And <i>Mouse Pad</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #114. 6147', 'https://poke.indrasaswita.com/sprites/animated/114.gif', 50, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 2, 'hair clip', 'This is the description of Hair Clip. And <i>Hair Clip</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #115. 5804', 'https://poke.indrasaswita.com/sprites/animated/115.gif', 100, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 10, 'sharpie', 'This is the description of Sharpie. And <i>Sharpie</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #116. 5000', 'https://poke.indrasaswita.com/sprites/animated/116.gif', 30, 125, 3, 'Sold', 8, NOW(), NOW()),
				(NULL, 7, 'radio', 'This is the description of Radio. And <i>Radio</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #117. 2914', 'https://poke.indrasaswita.com/sprites/animated/117.gif', 30, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 10, 'bottle', 'This is the description of Bottle. And <i>Bottle</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #118. 6975', 'https://poke.indrasaswita.com/sprites/animated/118.gif', 90, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 2, 'stockings', 'This is the description of Stockings. And <i>Stockings</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #119. 2407', 'https://poke.indrasaswita.com/sprites/animated/119.gif', 20, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 10, 'pencil holder', 'This is the description of Pencil Holder. And <i>Pencil Holder</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #120. 4370', 'https://poke.indrasaswita.com/sprites/animated/120.gif', 50, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 1, 'rope', 'This is the description of Rope. And <i>Rope</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #121. 5227', 'https://poke.indrasaswita.com/sprites/animated/121.gif', 40, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 8, 'thimble', 'This is the description of Thimble. And <i>Thimble</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #122. 7393', 'https://poke.indrasaswita.com/sprites/animated/122.gif', 20, 174, 2, 'Sold', 4, NOW(), NOW()),
				(NULL, 5, 'bag', 'This is the description of Bag. And <i>Bag</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #123. 3366', 'https://poke.indrasaswita.com/sprites/animated/123.gif', 30, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 5, 'speakers', 'This is the description of Speakers. And <i>Speakers</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #124. 9002', 'https://poke.indrasaswita.com/sprites/animated/124.gif', 60, 200, 5, 'Sold', 5, NOW(), NOW()),
				(NULL, 4, 'canvas', 'This is the description of Canvas. And <i>Canvas</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #125. 4440', 'https://poke.indrasaswita.com/sprites/animated/125.gif', 30, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 8, 'photo album', 'This is the description of Photo Album. And <i>Photo Album</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #126. 7899', 'https://poke.indrasaswita.com/sprites/animated/126.gif', 40, 168, 7, 'Sold', 7, NOW(), NOW()),
				(NULL, 7, 'money', 'This is the description of Money. And <i>Money</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #127. 6434', 'https://poke.indrasaswita.com/sprites/animated/127.gif', 90, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 9, 'wireless control', 'This is the description of Wireless Control. And <i>Wireless Control</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #128. 7886', 'https://poke.indrasaswita.com/sprites/animated/128.gif', 50, 197, 2, 'Sold', 7, NOW(), NOW()),
				(NULL, 7, 'box of baking soda', 'This is the description of Box Of Baking Soda. And <i>Box Of Baking Soda</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #129. 6322', 'https://poke.indrasaswita.com/sprites/animated/129.gif', 20, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 2, 'thermometer', 'This is the description of Thermometer. And <i>Thermometer</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #130. 3355', 'https://poke.indrasaswita.com/sprites/animated/130.gif', 50, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 7, 'nail clippers', 'This is the description of Nail Clippers. And <i>Nail Clippers</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #131. 8195', 'https://poke.indrasaswita.com/sprites/animated/131.gif', 80, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 8, 'umbrella', 'This is the description of Umbrella. And <i>Umbrella</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #132. 3289', 'https://poke.indrasaswita.com/sprites/animated/132.gif', 90, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 8, 'tv', 'This is the description of Tv. And <i>Tv</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #133. 9830', 'https://poke.indrasaswita.com/sprites/animated/133.gif', 10, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 1, 'pail', 'This is the description of Pail. And <i>Pail</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #134. 6362', 'https://poke.indrasaswita.com/sprites/animated/134.gif', 40, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 2, 'model car', 'This is the description of Model Car. And <i>Model Car</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #135. 7823', 'https://poke.indrasaswita.com/sprites/animated/135.gif', 100, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 8, 'sailboat', 'This is the description of Sailboat. And <i>Sailboat</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #136. 8522', 'https://poke.indrasaswita.com/sprites/animated/136.gif', 80, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 1, 'bonesaw', 'This is the description of Bonesaw. And <i>Bonesaw</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #137. 7017', 'https://poke.indrasaswita.com/sprites/animated/137.gif', 60, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 1, 'fridge', 'This is the description of Fridge. And <i>Fridge</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #138. 6424', 'https://poke.indrasaswita.com/sprites/animated/138.gif', 50, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 9, 'card', 'This is the description of Card. And <i>Card</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #139. 5954', 'https://poke.indrasaswita.com/sprites/animated/139.gif', 70, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 7, 'rhino', 'This is the description of Rhino. And <i>Rhino</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #140. 8458', 'https://poke.indrasaswita.com/sprites/animated/140.gif', 70, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 10, 'jar of jam', 'This is the description of Jar Of Jam. And <i>Jar Of Jam</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #141. 7037', 'https://poke.indrasaswita.com/sprites/animated/141.gif', 10, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 10, 'credit card', 'This is the description of Credit Card. And <i>Credit Card</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #142. 8812', 'https://poke.indrasaswita.com/sprites/animated/142.gif', 70, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 10, 'wristwatch', 'This is the description of Wristwatch. And <i>Wristwatch</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #143. 3876', 'https://poke.indrasaswita.com/sprites/animated/143.gif', 100, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 7, 'game CD', 'This is the description of Game Cd. And <i>Game Cd</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #144. 5698', 'https://poke.indrasaswita.com/sprites/animated/144.gif', 60, 137, 4, 'Sold', 2, NOW(), NOW()),
				(NULL, 9, 'frying pan', 'This is the description of Frying Pan. And <i>Frying Pan</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #145. 6368', 'https://poke.indrasaswita.com/sprites/animated/145.gif', 40, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 5, 'bandana', 'This is the description of Bandana. And <i>Bandana</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #146. 5245', 'https://poke.indrasaswita.com/sprites/animated/146.gif', 20, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 1, 'salt shaker', 'This is the description of Salt Shaker. And <i>Salt Shaker</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #147. 3055', 'https://poke.indrasaswita.com/sprites/animated/147.gif', 90, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 3, 'door', 'This is the description of Door. And <i>Door</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #148. 7117', 'https://poke.indrasaswita.com/sprites/animated/148.gif', 80, 149, 3, 'Sold', 6, NOW(), NOW()),
				(NULL, 2, 'extension cord', 'This is the description of Extension Cord. And <i>Extension Cord</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #149. 3294', 'https://poke.indrasaswita.com/sprites/animated/149.gif', 30, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 3, 'zipper', 'This is the description of Zipper. And <i>Zipper</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #150. 4244', 'https://poke.indrasaswita.com/sprites/animated/150.gif', 80, 190, 8, 'Sold', 5, NOW(), NOW()),
				(NULL, 3, 'fishing hook', 'This is the description of Fishing Hook. And <i>Fishing Hook</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #151. 8621', 'https://poke.indrasaswita.com/sprites/animated/151.gif', 90, 190, 5, 'Sold', 6, NOW(), NOW()),
				(NULL, 8, 'bottle of oil', 'This is the description of Bottle Of Oil. And <i>Bottle Of Oil</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #152. 5473', 'https://poke.indrasaswita.com/sprites/animated/152.gif', 60, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 6, 'magazine', 'This is the description of Magazine. And <i>Magazine</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #153. 6534', 'https://poke.indrasaswita.com/sprites/animated/153.gif', 50, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 7, 'craft book', 'This is the description of Craft Book. And <i>Craft Book</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #154. 6247', 'https://poke.indrasaswita.com/sprites/animated/154.gif', 10, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 6, 'chair', 'This is the description of Chair. And <i>Chair</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #155. 1806', 'https://poke.indrasaswita.com/sprites/animated/155.gif', 90, 171, 4, 'Sold', 4, NOW(), NOW()),
				(NULL, 7, 'rug', 'This is the description of Rug. And <i>Rug</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #156. 2063', 'https://poke.indrasaswita.com/sprites/animated/156.gif', 100, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 9, 'can of beans', 'This is the description of Can Of Beans. And <i>Can Of Beans</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #157. 7718', 'https://poke.indrasaswita.com/sprites/animated/157.gif', 10, 142, 2, 'Sold', 8, NOW(), NOW()),
				(NULL, 10, 'feather', 'This is the description of Feather. And <i>Feather</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #158. 6184', 'https://poke.indrasaswita.com/sprites/animated/158.gif', 20, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 10, 'piece of gum', 'This is the description of Piece Of Gum. And <i>Piece Of Gum</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #159. 7846', 'https://poke.indrasaswita.com/sprites/animated/159.gif', 80, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 6, 'water bottle', 'This is the description of Water Bottle. And <i>Water Bottle</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #160. 2066', 'https://poke.indrasaswita.com/sprites/animated/160.gif', 40, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 8, 'shark', 'This is the description of Shark. And <i>Shark</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #161. 8786', 'https://poke.indrasaswita.com/sprites/animated/161.gif', 50, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 5, 'broccoli', 'This is the description of Broccoli. And <i>Broccoli</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #162. 9539', 'https://poke.indrasaswita.com/sprites/animated/162.gif', 10, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 2, 'seat belt', 'This is the description of Seat Belt. And <i>Seat Belt</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #163. 9176', 'https://poke.indrasaswita.com/sprites/animated/163.gif', 90, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 8, 'white out', 'This is the description of White Out. And <i>White Out</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #164. 7717', 'https://poke.indrasaswita.com/sprites/animated/164.gif', 30, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 9, 'comic book', 'This is the description of Comic Book. And <i>Comic Book</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #165. 6494', 'https://poke.indrasaswita.com/sprites/animated/165.gif', 30, 193, 1, 'Sold', 8, NOW(), NOW()),
				(NULL, 9, 'plush dog', 'This is the description of Plush Dog. And <i>Plush Dog</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #166. 4558', 'https://poke.indrasaswita.com/sprites/animated/166.gif', 70, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 8, 'tweezers', 'This is the description of Tweezers. And <i>Tweezers</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #167. 4077', 'https://poke.indrasaswita.com/sprites/animated/167.gif', 50, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 8, 'balloon', 'This is the description of Balloon. And <i>Balloon</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #168. 8064', 'https://poke.indrasaswita.com/sprites/animated/168.gif', 70, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 1, 'lace', 'This is the description of Lace. And <i>Lace</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #169. 9434', 'https://poke.indrasaswita.com/sprites/animated/169.gif', 60, 175, 2, 'Sold', 3, NOW(), NOW()),
				(NULL, 6, 'plush dinosaur', 'This is the description of Plush Dinosaur. And <i>Plush Dinosaur</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #170. 7899', 'https://poke.indrasaswita.com/sprites/animated/170.gif', 60, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 3, 'keys', 'This is the description of Keys. And <i>Keys</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #171. 1892', 'https://poke.indrasaswita.com/sprites/animated/171.gif', 10, NULL, NULL, 'Draft', 7, NOW(), NOW()),
				(NULL, 3, 'jar of peanut butter', 'This is the description of Jar Of Peanut Butter. And <i>Jar Of Peanut Butter</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #172. 2625', 'https://poke.indrasaswita.com/sprites/animated/172.gif', 30, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 4, 'pepper shaker', 'This is the description of Pepper Shaker. And <i>Pepper Shaker</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #173. 3937', 'https://poke.indrasaswita.com/sprites/animated/173.gif', 90, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 7, 'conditioner', 'This is the description of Conditioner. And <i>Conditioner</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #174. 1119', 'https://poke.indrasaswita.com/sprites/animated/174.gif', 70, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 4, 'apple', 'This is the description of Apple. And <i>Apple</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #175. 7958', 'https://poke.indrasaswita.com/sprites/animated/175.gif', 90, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 7, 'pasta strainer', 'This is the description of Pasta Strainer. And <i>Pasta Strainer</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #176. 3467', 'https://poke.indrasaswita.com/sprites/animated/176.gif', 70, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 9, 'hanger', 'This is the description of Hanger. And <i>Hanger</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #177. 2633', 'https://poke.indrasaswita.com/sprites/animated/177.gif', 20, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 7, 'eraser', 'This is the description of Eraser. And <i>Eraser</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #178. 7978', 'https://poke.indrasaswita.com/sprites/animated/178.gif', 80, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 1, 'plush cat', 'This is the description of Plush Cat. And <i>Plush Cat</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #179. 4127', 'https://poke.indrasaswita.com/sprites/animated/179.gif', 30, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 3, 'book of matches', 'This is the description of Book Of Matches. And <i>Book Of Matches</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #180. 7802', 'https://poke.indrasaswita.com/sprites/animated/180.gif', 30, NULL, NULL, 'Draft', 8, NOW(), NOW()),
				(NULL, 8, 'tea cup', 'This is the description of Tea Cup. And <i>Tea Cup</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #181. 6557', 'https://poke.indrasaswita.com/sprites/animated/181.gif', 60, NULL, NULL, 'Draft', 2, NOW(), NOW()),
				(NULL, 8, 'socks', 'This is the description of Socks. And <i>Socks</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #182. 2920', 'https://poke.indrasaswita.com/sprites/animated/182.gif', 50, 119, 8, 'Sold', 6, NOW(), NOW()),
				(NULL, 8, 'box of chalk', 'This is the description of Box Of Chalk. And <i>Box Of Chalk</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #183. 5055', 'https://poke.indrasaswita.com/sprites/animated/183.gif', 100, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 4, 'bottle of ink', 'This is the description of Bottle Of Ink. And <i>Bottle Of Ink</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #184. 9294', 'https://poke.indrasaswita.com/sprites/animated/184.gif', 90, 126, 7, 'Sold', 6, NOW(), NOW()),
				(NULL, 1, 'ipod', 'This is the description of Ipod. And <i>Ipod</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #185. 3562', 'https://poke.indrasaswita.com/sprites/animated/185.gif', 40, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 3, 'nail', 'This is the description of Nail. And <i>Nail</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #186. 1451', 'https://poke.indrasaswita.com/sprites/animated/186.gif', 60, 196, 6, 'Sold', 3, NOW(), NOW()),
				(NULL, 2, 'belt', 'This is the description of Belt. And <i>Belt</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #187. 7481', 'https://poke.indrasaswita.com/sprites/animated/187.gif', 50, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 3, 'bookmark', 'This is the description of Bookmark. And <i>Bookmark</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #188. 3543', 'https://poke.indrasaswita.com/sprites/animated/188.gif', 70, NULL, NULL, 'Draft', 3, NOW(), NOW()),
				(NULL, 6, 'chicken', 'This is the description of Chicken. And <i>Chicken</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #189. 7034', 'https://poke.indrasaswita.com/sprites/animated/189.gif', 90, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 9, 'lip gloss', 'This is the description of Lip Gloss. And <i>Lip Gloss</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #190. 7550', 'https://poke.indrasaswita.com/sprites/animated/190.gif', 40, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 10, 'shampoo', 'This is the description of Shampoo. And <i>Shampoo</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #191. 8964', 'https://poke.indrasaswita.com/sprites/animated/191.gif', 70, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 2, 'pants', 'This is the description of Pants. And <i>Pants</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #192. 3540', 'https://poke.indrasaswita.com/sprites/animated/192.gif', 10, 167, 7, 'Sold', 6, NOW(), NOW()),
				(NULL, 8, 'outlet', 'This is the description of Outlet. And <i>Outlet</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #193. 8180', 'https://poke.indrasaswita.com/sprites/animated/193.gif', 20, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 9, 'clock', 'This is the description of Clock. And <i>Clock</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #194. 8141', 'https://poke.indrasaswita.com/sprites/animated/194.gif', 70, NULL, NULL, 'Draft', 4, NOW(), NOW()),
				(NULL, 10, 'beaded bracelet', 'This is the description of Beaded Bracelet. And <i>Beaded Bracelet</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #195. 1112', 'https://poke.indrasaswita.com/sprites/animated/195.gif', 10, 174, 2, 'Sold', 8, NOW(), NOW()),
				(NULL, 1, 'ball of yarn', 'This is the description of Ball Of Yarn. And <i>Ball Of Yarn</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #196. 2436', 'https://poke.indrasaswita.com/sprites/animated/196.gif', 100, NULL, NULL, 'Draft', 6, NOW(), NOW()),
				(NULL, 3, 'plush bear', 'This is the description of Plush Bear. And <i>Plush Bear</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #197. 5881', 'https://poke.indrasaswita.com/sprites/animated/197.gif', 80, NULL, NULL, 'Draft', 1, NOW(), NOW()),
				(NULL, 9, 'marble', 'This is the description of Marble. And <i>Marble</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #198. 7203', 'https://poke.indrasaswita.com/sprites/animated/198.gif', 40, NULL, NULL, 'Draft', 5, NOW(), NOW()),
				(NULL, 4, 'small pouch', 'This is the description of Small Pouch. And <i>Small Pouch</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #199. 1708', 'https://poke.indrasaswita.com/sprites/animated/199.gif', 30, 191, 6, 'Sold', 3, NOW(), NOW()),
				(NULL, 2, 'toilet', 'This is the description of Toilet. And <i>Toilet</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #200. 4860', 'https://poke.indrasaswita.com/sprites/animated/200.gif', 100, 146, 2, 'Sold', 1, NOW(), NOW()),
				(NULL, 10, 'leg warmers', 'This is the description of Leg Warmers. And <i>Leg Warmers</i> is also use for help the people around the world to make a <b>better life</b>. This is the sample description #201. 2875', 'https://poke.indrasaswita.com/sprites/animated/201.gif', 30, NULL, NULL, 'Draft', 2, NOW(), NOW());

			INSERT INTO itemcategories
			VALUES 
				(NULL, 'Mobile', 'fadMobile', NOW(), NOW()),
				(NULL, 'Permanent', 'fadHouse', NOW(), NOW()),
				(NULL, 'Break', 'fadMugHot', NOW(), NOW()),
				(NULL, 'Rare', 'fadHourglass', NOW(), NOW()),
				(NULL, 'Food', 'fadFrenchFries', NOW(), NOW()),
				(NULL, 'Heroic', 'fadMask', NOW(), NOW()),
				(NULL, 'Unique', 'fadFingerprint', NOW(), NOW()),
				(NULL, 'Game', 'fadGamepadAlt', NOW(), NOW()),
				(NULL, 'Divine', 'fadSun', NOW(), NOW()),
				(NULL, 'Music', 'fadDrum', NOW(), NOW());


		");
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('users');
		Schema::dropIfExists('itemusers');
		Schema::dropIfExists('items');
		Schema::dropIfExists('itemcategories');
	}
}
